import { useState } from 'react';
import { motion } from 'framer-motion';

const SAMPLE_NOTES = `Attendees: Sarah (PM), John (Dev), Maria (Design), Tom (Marketing)
Date: Monday 10am

Agenda:
- Q3 roadmap review
- New feature prioritization
- Budget allocation
- Launch timeline

Discussion:
- Sarah presented Q3 goals: launch mobile app, increase DAU by 30%
- John confirmed backend is ready, needs 2 more weeks for testing
- Maria showed new UI mockups, team agreed on direction
- Tom wants to delay launch by 1 week for marketing campaign prep

Decisions:
- Launch date set for September 15th
- Budget approved: $50k for marketing
- John to finish testing by August 30th
- Maria to deliver final assets by September 1st

Action Items:
- John: Complete backend testing by Aug 30
- Maria: Finalize assets by Sep 1
- Tom: Prepare marketing materials by Sep 8
- Sarah: Send launch checklist to all by end of week`;

function summarize(notes: string): string {
  const lines = notes.split('\n').filter(l => l.trim());
  const decisions = lines.filter(l => l.includes('decided') || l.includes('agreed') || l.includes('set') || l.includes('approved'));
  const actions = lines.filter(l => l.includes(':') && (l.includes('to ') || l.includes('will ')));

  return `## 📋 Meeting Summary

**Date Processed:** ${new Date().toLocaleDateString('en', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

---

### 🎯 Key Outcomes
${decisions.slice(0, 4).map(d => `• ${d.trim()}`).join('\n') || '• Meeting notes processed successfully'}

### ✅ Action Items
${actions.slice(0, 5).map(a => `• ${a.trim()}`).join('\n') || '• Review and follow up on discussed items'}

### 📊 Next Steps
1. Distribute this summary to all attendees
2. Schedule follow-up meeting if needed
3. Update project management tools with action items
4. Set reminders for all deadlines mentioned

---
*Auto-generated by EduPro Meeting Notes Summarizer*`;
}

export default function MeetingNotes() {
  const [notes, setNotes] = useState(SAMPLE_NOTES);
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const generate = () => {
    setLoading(true);
    setTimeout(() => {
      setSummary(summarize(notes));
      setLoading(false);
    }, 1500);
  };

  const copy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="animate-fade-in">
      <div className="tool-page-header">
        <div style={{ background: 'rgba(6,182,212,0.1)', width: 52, height: 52, borderRadius: 'var(--radius-lg)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 26 }}>📝</div>
        <div>
          <div className="tool-page-title">Meeting Notes Summarizer</div>
          <div className="tool-page-desc">Paste raw meeting notes → get clean, structured summary</div>
        </div>
      </div>

